apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: nginx-skaffold
    context: .
  local: {}
# deploy:
#   kubectl:
#     manifests:
#     - k8s-*
profiles:
  - name: local-az
    deploy:
      kustomize:
        paths:
        - k8s/local-az