apiVersion: skaffold/v2beta21
kind: Config
build:
  artifacts:
  - image: monkey-ui
    custom:
      buildCommand: yarn install && yarn build && docker build -t monkey-ui:latest
        --build-arg BUILD_IMAGE=registry.access.redhat.com/ubi8/nginx-118:latest -f
        container/monkey-ui/Dockerfile .
  tagPolicy:
    sha256: {}
  local: {}
deploy:
  kubectl:
    manifests:
    - k8s/*
