apiVersion: apps/v1
kind: Deployment
metadata:
    name: monkey-ui
spec:
    selector:
      matchLabels:
        app: monkey-ui
    template:
      metadata:
        labels:
            app: monkey-ui
      spec:
        containers:
        - name: monkey-ui
          image: monkey-ui:latest

