apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: myhelsana/template
    newName: monkey-ui
    newTag: latest

namespace: default

commonLabels:
  app: monkey-ui-frontend
  appGroup: demo

resources:
  - ../../base

# Patch Deployment
patchesStrategicMerge:
  - patch-service.yaml
