apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  selector: {}
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: myhelsana/template
          name: monkey-ui
          imagePullPolicy: IfNotPresent
      restartPolicy: Always


