apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: monkey-ui-

# Resources
resources:
  - deployment.yaml
  - service.yaml

# otherwise the name wil be namePrefix-app-nameSuffix
patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: frontend
    target:
      kind: Deployment
      name: .*
  - patch: |-
      - op: replace
        path: /metadata/name
        value: frontend
    target:
      kind: Service
      name: .*
  - target:
      kind: PrometheusRule
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: frontend
  - target:
      kind: Route
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: frontend
